import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    initial=True
    dependencies=[("evento","0001_initial")]
    operations=[
      migrations.CreateModel(name="Torneo",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("nombre",models.CharField(max_length=120)),("slug",models.SlugField(unique=True)),("juego",models.CharField(max_length=120)),("modalidad",models.CharField(choices=[("individual","Individual"),("equipo","Equipo")],max_length=10)),("jugadores_por_equipo",models.PositiveSmallIntegerField()),("cupo_equipos",models.PositiveSmallIntegerField()),("estado",models.CharField(choices=[("inscripcion","Inscripcion"),("sorteado","Sorteado"),("en_curso","En Curso"),("finalizado","Finalizado")],default="inscripcion",max_length=15)),("hora_inicio",models.TimeField()),("hora_fin",models.TimeField()),("reglas",models.TextField(blank=True)),("cierre_inscripciones",models.DateTimeField())]),
      migrations.CreateModel(name="Equipo",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("nombre",models.CharField(max_length=80)),("estado",models.CharField(choices=[("confirmado","Confirmado"),("espera","Espera"),("retirado","Retirado")],max_length=12)),("seed",models.PositiveSmallIntegerField(blank=True,null=True)),("creado_en",models.DateTimeField(auto_now_add=True)),("capitan",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="capitanias",to="evento.asistente")),("torneo",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="equipos",to="torneos.torneo"))],options={"unique_together":{("torneo","nombre")}}),
      migrations.CreateModel(name="Integrante",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("gamertag",models.CharField(blank=True,max_length=60)),("asistente",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="participaciones",to="evento.asistente")),("equipo",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="integrantes",to="torneos.equipo"))],options={"unique_together":{("equipo","asistente")}}),
      migrations.CreateModel(name="Partida",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("ronda",models.PositiveSmallIntegerField()),("orden",models.PositiveSmallIntegerField()),("score_a",models.PositiveSmallIntegerField(default=0)),("score_b",models.PositiveSmallIntegerField(default=0)),("estado",models.CharField(choices=[("pendiente","Pendiente"),("en_curso","En Curso"),("finalizada","Finalizada")],default="pendiente",max_length=12)),("slot_siguiente",models.CharField(blank=True,choices=[("A","A"),("B","B")],max_length=1,null=True)),("equipo_a",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="+",to="torneos.equipo")),("equipo_b",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="+",to="torneos.equipo")),("ganador",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="victorias",to="torneos.equipo")),("siguiente_partida",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="origen",to="torneos.partida")),("torneo",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="partidas",to="torneos.torneo"))],options={"ordering":["ronda","orden"],"unique_together":{("torneo","ronda","orden")}})]
