# Generated by Django 5.2.17 on 2026-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="acreditado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipo",
            name="acreditado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partida",
            name="por_walkover",
            field=models.BooleanField(default=False),
        ),
    ]
