# Generated by Django 5.2.17 on 2026-09-14 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneos", "0002_equipo_acreditado_equipo_acreditado_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneo",
            name="llave_publicada",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PromocionEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promociones",
                        to="torneos.equipo",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promociones",
                        to="torneos.torneo",
                    ),
                ),
            ],
        ),
    ]
