# Generated by Django 5.2.17 on 2026-09-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneos", "0003_torneo_llave_publicada_promocionespera"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneo",
            name="bloque",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="torneo",
            name="equipamiento",
            field=models.CharField(
                choices=[("pc", "PC"), ("consola", "Consola")],
                default="pc",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="torneo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("inscripcion", "Inscripcion"),
                    ("cerrado", "Cerrado"),
                    ("sorteado", "Sorteado"),
                    ("en_curso", "En Curso"),
                    ("finalizado", "Finalizado"),
                ],
                default="inscripcion",
                max_length=15,
            ),
        ),
    ]
