# Generated by Django 5.2.17 on 2026-09-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneos", "0006_cambiointegrante_origen"),
    ]

    operations = [
        migrations.AddField(
            model_name="cambiointegrante",
            name="tras_cierre",
            field=models.BooleanField(default=False),
        ),
    ]
