# Generated by Django 5.2.17 on 2026-09-14 22:45

import django.db.models.deletion
from django.db import migrations, models


def migrar_areas(apps, schema_editor):
    Area = apps.get_model("evento", "Area")
    Asistente = apps.get_model("evento", "Asistente")
    datos = {
        "informatica": ("Informática, Ciberseguridad y Telecomunicaciones", "informatica-ciberseguridad-y-telecomunicaciones", 10),
        "diseno": ("Diseño e Industria Digital", "diseno-e-industria-digital", 9),
        "automatizacion": ("Automatización, Electrónica y Robótica", "automatizacion-electronica-y-robotica", 8),
    }
    for valor, (nombre, slug, orden) in datos.items():
        area, _ = Area.objects.get_or_create(slug=slug, defaults={"nombre": nombre, "orden": orden})
        Asistente.objects.filter(area_anterior=valor).update(area=area)


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="asistente", old_name="area", new_name="area_anterior"),
        migrations.RenameField(model_name="asistente", old_name="carrera", new_name="carrera_anterior"),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("orden", models.PositiveSmallIntegerField()),
                ("activa", models.BooleanField(default=True)),
            ],
            options={"ordering": ["orden", "nombre"]},
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("activa", models.BooleanField(default=True)),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="carreras", to="evento.area")),
            ],
            options={"ordering": ["nombre"], "unique_together": {("area", "nombre")}},
        ),
        migrations.AddField(
            model_name="asistente", name="area",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="evento.area"),
        ),
        migrations.AddField(
            model_name="asistente", name="carrera",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="evento.carrera"),
        ),
        migrations.RunPython(migrar_areas, migrations.RunPython.noop),
        migrations.RemoveField(model_name="asistente", name="area_anterior"),
        migrations.RemoveField(model_name="asistente", name="carrera_anterior"),
    ]
