# Generated by Django 5.2.17 on 2026-09-14 23:11

import evento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0002_catalogo_areas_carreras"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cupo_asistentes", models.PositiveSmallIntegerField(default=120)),
                ("registro_abierto", models.BooleanField(default=True)),
                (
                    "completos_por_asistente",
                    models.PositiveSmallIntegerField(default=2),
                ),
                ("mensaje_cupos_agotados", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AlterField(
            model_name="asistente",
            name="completos_asignados",
            field=models.PositiveSmallIntegerField(
                default=evento.models.completos_por_defecto
            ),
        ),
    ]
