# Generated by Django 5.2.17 on 2026-09-15 19:09

import django.db.models.deletion
import evento.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0003_configuracionevento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionevento",
            name="areas_prioritarias",
            field=models.ManyToManyField(
                blank=True,
                related_name="configuraciones_prioritarias",
                to="evento.area",
            ),
        ),
        migrations.AddField(
            model_name="configuracionevento",
            name="registro_restringido",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AlumnoHabilitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        unique=True,
                        validators=[evento.validators.validar_rut],
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("apellido", models.CharField(max_length=60)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("lote", models.CharField(blank=True, max_length=60)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "carrera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_habilitados",
                        to="evento.carrera",
                    ),
                ),
            ],
        ),
    ]
