# Generated by Django 5.2.17 on 2026-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0004_configuracionevento_areas_prioritarias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionevento",
            name="restriccion_todos_los_tipos",
            field=models.BooleanField(default=False),
        ),
    ]
